export const scopes = {
    CHC: 'CHC',
    CHD: 'CHD',
    CHR: 'CHR',
    CHU: 'CHU',
    DCC: 'DCC',
    DCD: 'DCD',
    DCQR: 'DCQR',
    DCR: 'DCR',
    DCU: 'DCU',
    OGC: 'OGC',
    OGD: 'OGD',
    OGR: 'OGR',
    OGU: 'OGU',
    UC: 'UC',
    UD: 'UD',
    UR: 'UR',
    UU: 'UU',
}
